// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkevmgznnldkoismjtqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZXZtZ3pubmxka29pc21qdHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjE5MTgsImV4cCI6MjA2OTEzNzkxOH0.xDPPCEJ9PaIqjTt288lwClfooIexBkyKlS2T17I6Mp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});